<?php

namespace Database\Seeders;

use App\Models\Destination;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DestinationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $destinations = [
            [
                'name' => 'Serengeti National Park',
                'slug' => 'serengeti-national-park',
                'country' => 'Tanzania',
                'region' => 'Northern',
                'description' => 'World-famous for the Great Migration, Serengeti offers unparalleled wildlife viewing with lions, elephants, and millions of wildebeest and zebras.',
                'image_url' => 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80',
                'visa_required' => false,
                'visa_type' => null,
                'flight_duration' => '1-2 hours from Arusha',
                'best_season' => 'June - October (Dry season)',
                'highlights' => ['Great Migration', 'Big Five', 'Hot Air Balloon Safaris', 'Savanna Plains'],
                'is_popular' => true,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Ngorongoro Crater',
                'slug' => 'ngorongoro-crater',
                'country' => 'Tanzania',
                'region' => 'Northern',
                'description' => 'A UNESCO World Heritage Site, this massive volcanic caldera hosts dense wildlife populations including the rare black rhino.',
                'image_url' => 'https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=800&q=80',
                'visa_required' => false,
                'visa_type' => null,
                'flight_duration' => '1 hour from Arusha',
                'best_season' => 'June - October',
                'highlights' => ['World\'s Largest Caldera', 'Black Rhinos', 'Dense Wildlife', 'UNESCO Heritage Site'],
                'is_popular' => true,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Mount Kilimanjaro',
                'slug' => 'mount-kilimanjaro',
                'country' => 'Tanzania',
                'region' => 'Northern',
                'description' => 'Africa\'s highest peak and the world\'s tallest free-standing mountain. A challenging but rewarding climb through diverse ecosystems.',
                'image_url' => 'https://images.unsplash.com/photo-1609766857071-0e0b3a9f4c19?w=800&q=80',
                'visa_required' => false,
                'visa_type' => null,
                'flight_duration' => '1 hour from Arusha',
                'best_season' => 'January - March, June - October',
                'highlights' => ['Africa\'s Highest Peak', '7 Climbing Routes', 'Diverse Ecosystems', 'Snow-Capped Summit'],
                'is_popular' => true,
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Zanzibar Beaches',
                'slug' => 'zanzibar-beaches',
                'country' => 'Tanzania',
                'region' => 'Coastal',
                'description' => 'Pristine white sand beaches, crystal clear waters, and rich Swahili culture. Perfect for relaxation, diving, and cultural exploration.',
                'image_url' => 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80',
                'visa_required' => false,
                'visa_type' => null,
                'flight_duration' => '30 minutes from Dar es Salaam',
                'best_season' => 'June - October, December - February',
                'highlights' => ['Stone Town', 'Spice Tours', 'Dolphin Tours', 'Historic Slave Markets'],
                'is_popular' => true,
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'Tarangire National Park',
                'slug' => 'tarangire-national-park',
                'country' => 'Tanzania',
                'region' => 'Northern',
                'description' => 'Famous for its massive elephant herds and ancient baobab trees. Less crowded than other parks with excellent bird watching.',
                'image_url' => 'https://images.unsplash.com/photo-1549366021-9f761d450615?w=800&q=80',
                'visa_required' => false,
                'visa_type' => null,
                'flight_duration' => '2 hours from Arusha',
                'best_season' => 'June - October',
                'highlights' => ['Large Elephant Herds', 'Ancient Baobab Trees', 'Bird Watching', 'Less Crowded'],
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'name' => 'Lake Manyara National Park',
                'slug' => 'lake-manyara-national-park',
                'country' => 'Tanzania',
                'region' => 'Northern',
                'description' => 'Known for tree-climbing lions, diverse bird life, and stunning alkaline lake views. Compact park perfect for day trips.',
                'image_url' => 'https://images.unsplash.com/photo-1549366021-9f761d450615?w=800&q=80',
                'visa_required' => false,
                'visa_type' => null,
                'flight_duration' => '1.5 hours from Arusha',
                'best_season' => 'June - October',
                'highlights' => ['Tree-Climbing Lions', 'Flamingos', 'Diverse Bird Life', 'Alkaline Lake'],
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'name' => 'Selous Game Reserve',
                'slug' => 'selous-game-reserve',
                'country' => 'Tanzania',
                'region' => 'Southern',
                'description' => 'Africa\'s largest game reserve with pristine wilderness. Excellent for walking safaris, boat trips, and wild dog sightings.',
                'image_url' => 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80',
                'visa_required' => false,
                'visa_type' => null,
                'flight_duration' => '1 hour from Dar es Salaam',
                'best_season' => 'June - October',
                'highlights' => ['Walking Safaris', 'Boat Safaris', 'Wild Dogs', 'Pristine Wilderness'],
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'name' => 'Ruaha National Park',
                'slug' => 'ruaha-national-park',
                'country' => 'Tanzania',
                'region' => 'Southern',
                'description' => 'Tanzania\'s largest national park with dramatic landscapes and huge elephant populations. Remote and untouched wilderness.',
                'image_url' => 'https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=800&q=80',
                'visa_required' => false,
                'visa_type' => null,
                'flight_duration' => '2 hours from Dar es Salaam',
                'best_season' => 'June - October',
                'highlights' => ['Largest National Park', 'Huge Elephant Populations', 'Remote Wilderness', 'Dramatic Landscapes'],
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'name' => 'Mafia Island',
                'slug' => 'mafia-island',
                'country' => 'Tanzania',
                'region' => 'Coastal',
                'description' => 'A hidden gem for diving enthusiasts with pristine coral reefs, whale sharks, and marine turtles. Perfect for underwater adventures.',
                'image_url' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
                'visa_required' => false,
                'visa_type' => null,
                'flight_duration' => '30 minutes from Dar es Salaam',
                'best_season' => 'October - March',
                'highlights' => ['Whale Sharks', 'Coral Reefs', 'Marine Turtles', 'Diving Paradise'],
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'name' => 'Pemba Island',
                'slug' => 'pemba-island',
                'country' => 'Tanzania',
                'region' => 'Coastal',
                'description' => 'The green island of Zanzibar archipelago with lush hills, spice farms, and excellent diving spots. Authentic Swahili culture.',
                'image_url' => 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80',
                'visa_required' => false,
                'visa_type' => null,
                'flight_duration' => '45 minutes from Zanzibar',
                'best_season' => 'June - October',
                'highlights' => ['Spice Farms', 'Diving Spots', 'Lush Hills', 'Authentic Culture'],
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'name' => 'Arusha National Park',
                'slug' => 'arusha-national-park',
                'country' => 'Tanzania',
                'region' => 'Northern',
                'description' => 'Compact park with diverse landscapes including Mount Meru, Momella Lakes, and Ngurdoto Crater. Great for day trips and hiking.',
                'image_url' => 'https://images.unsplash.com/photo-1609766857071-0e0b3a9f4c19?w=800&q=80',
                'visa_required' => false,
                'visa_type' => null,
                'flight_duration' => '30 minutes from Arusha',
                'best_season' => 'June - October',
                'highlights' => ['Mount Meru', 'Momella Lakes', 'Ngurdoto Crater', 'Canoe Safaris'],
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 11,
            ],
            [
                'name' => 'Mahale Mountains National Park',
                'slug' => 'mahale-mountains-national-park',
                'country' => 'Tanzania',
                'region' => 'Western',
                'description' => 'Home to the largest population of chimpanzees in Tanzania. Remote wilderness with stunning Lake Tanganyika views.',
                'image_url' => 'https://images.unsplash.com/photo-1549366021-9f761d450615?w=800&q=80',
                'visa_required' => false,
                'visa_type' => null,
                'flight_duration' => '4 hours from Dar es Salaam',
                'best_season' => 'May - October',
                'highlights' => ['Chimpanzee Tracking', 'Lake Tanganyika', 'Remote Wilderness', 'Hiking Trails'],
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 12,
            ],
            [
                'name' => 'Gombe Stream National Park',
                'slug' => 'gombe-stream-national-park',
                'country' => 'Tanzania',
                'region' => 'Western',
                'description' => 'Famous for Jane Goodall\'s chimpanzee research. Small park with incredible primate encounters and pristine forest.',
                'image_url' => 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80',
                'visa_required' => false,
                'visa_type' => null,
                'flight_duration' => '4 hours from Kigoma',
                'best_season' => 'May - October',
                'highlights' => ['Chimpanzee Research', 'Jane Goodall Legacy', 'Pristine Forest', 'Primate Encounters'],
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 13,
            ],
            [
                'name' => 'Katavi National Park',
                'slug' => 'katavi-national-park',
                'country' => 'Tanzania',
                'region' => 'Western',
                'description' => 'Tanzania\'s third-largest park with massive buffalo herds and hippos. Remote wilderness with exceptional wildlife densities.',
                'image_url' => 'https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=800&q=80',
                'visa_required' => false,
                'visa_type' => null,
                'flight_duration' => '3 hours from Dar es Salaam',
                'best_season' => 'May - October',
                'highlights' => ['Massive Buffalo Herds', 'Hippo Concentrations', 'Remote Wilderness', 'Exceptional Wildlife'],
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 14,
            ],
            [
                'name' => 'Rubondo Island National Park',
                'slug' => 'rubondo-island-national-park',
                'country' => 'Tanzania',
                'region' => 'Lake Victoria',
                'description' => 'An island paradise on Lake Victoria with introduced chimpanzees, elephants, and diverse bird life. Fishing and bird watching paradise.',
                'image_url' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
                'visa_required' => false,
                'visa_type' => null,
                'flight_duration' => '2 hours from Mwanza',
                'best_season' => 'June - October',
                'highlights' => ['Lake Victoria', 'Chimpanzees', 'Bird Watching', 'Fishing Paradise'],
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 15,
            ],
        ];

        foreach ($destinations as $destination) {
            Destination::updateOrCreate(
                ['slug' => $destination['slug']],
                $destination
            );
        }

        $this->command->info('Destinations seeded successfully.');
    }
}
