<?php

namespace Database\Seeders;

use App\Models\Destination;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DestinationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $destinations = [
            // International Destinations
            [
                'name' => 'Dubai',
                'slug' => 'dubai',
                'country' => 'UAE',
                'region' => 'Middle East',
                'description' => 'A futuristic city with iconic skyscrapers, luxury shopping, and desert adventures. Home to the Burj Khalifa and Palm Jumeirah.',
                'image_url' => 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80',
                'visa_required' => true,
                'visa_type' => 'Tourist/Visit Visa',
                'flight_duration' => '5 hours from Dar es Salaam',
                'best_season' => 'November - March',
                'highlights' => ['Burj Khalifa', 'Desert Safari', 'Luxury Shopping', 'Palm Jumeirah'],
                'is_popular' => true,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'London',
                'slug' => 'london',
                'country' => 'United Kingdom',
                'region' => 'Europe',
                'description' => 'Historic city with iconic landmarks, world-class museums, and vibrant culture. Perfect for business and leisure travel.',
                'image_url' => 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&q=80',
                'visa_required' => true,
                'visa_type' => 'UK Standard Visitor Visa',
                'flight_duration' => '9 hours from Dar es Salaam',
                'best_season' => 'April - September',
                'highlights' => ['Big Ben', 'British Museum', 'Tower Bridge', 'West End'],
                'is_popular' => true,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Istanbul',
                'slug' => 'istanbul',
                'country' => 'Turkey',
                'region' => 'Europe/Asia',
                'description' => 'A city straddling two continents with rich history, stunning architecture, and vibrant bazaars.',
                'image_url' => 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800&q=80',
                'visa_required' => true,
                'visa_type' => 'E-Visa',
                'flight_duration' => '7 hours from Dar es Salaam',
                'best_season' => 'April - May, September - October',
                'highlights' => ['Hagia Sophia', 'Grand Bazaar', 'Bosphorus', 'Blue Mosque'],
                'is_popular' => true,
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'New York',
                'slug' => 'new-york',
                'country' => 'United States',
                'region' => 'North America',
                'description' => 'The city that never sleeps with iconic landmarks, Broadway shows, and diverse neighborhoods.',
                'image_url' => 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&q=80',
                'visa_required' => true,
                'visa_type' => 'B1/B2 Visa',
                'flight_duration' => '15 hours from Dar es Salaam',
                'best_season' => 'April - June, September - November',
                'highlights' => ['Statue of Liberty', 'Times Square', 'Central Park', 'Broadway'],
                'is_popular' => true,
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'Paris',
                'slug' => 'paris',
                'country' => 'France',
                'region' => 'Europe',
                'description' => 'The city of love with iconic Eiffel Tower, world-class art museums, and exquisite cuisine.',
                'image_url' => 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80',
                'visa_required' => true,
                'visa_type' => 'Schengen Visa',
                'flight_duration' => '8 hours from Dar es Salaam',
                'best_season' => 'April - June, September - October',
                'highlights' => ['Eiffel Tower', 'Louvre Museum', 'Champs-Élysées', 'Notre-Dame'],
                'is_popular' => true,
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'name' => 'Tokyo',
                'slug' => 'tokyo',
                'country' => 'Japan',
                'region' => 'Asia',
                'description' => 'A vibrant metropolis blending ancient traditions with cutting-edge technology and pop culture.',
                'image_url' => 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80',
                'visa_required' => true,
                'visa_type' => 'E-Visa',
                'flight_duration' => '14 hours from Dar es Salaam',
                'best_season' => 'March - May, October - November',
                'highlights' => ['Shibuya Crossing', 'Senso-ji Temple', 'Mount Fuji', 'Cherry Blossoms'],
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'name' => 'Sydney',
                'slug' => 'sydney',
                'country' => 'Australia',
                'region' => 'Oceania',
                'description' => 'Iconic harbor city with stunning beaches, opera house, and vibrant outdoor lifestyle.',
                'image_url' => 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800&q=80',
                'visa_required' => true,
                'visa_type' => 'Visitor Visa',
                'flight_duration' => '16 hours from Dar es Salaam',
                'best_season' => 'September - November, March - May',
                'highlights' => ['Opera House', 'Harbour Bridge', 'Bondi Beach', 'Taronga Zoo'],
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 7,
            ],
            // Tanzania Destinations
            [
                'name' => 'Serengeti National Park',
                'slug' => 'serengeti-national-park',
                'country' => 'Tanzania',
                'region' => 'Northern',
                'description' => 'World-famous for the Great Migration, Serengeti offers unparalleled wildlife viewing with lions, elephants, and millions of wildebeest and zebras.',
                'image_url' => 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80',
                'visa_required' => false,
                'visa_type' => null,
                'flight_duration' => '1-2 hours from Arusha',
                'best_season' => 'June - October (Dry season)',
                'highlights' => ['Great Migration', 'Big Five', 'Hot Air Balloon Safaris', 'Savanna Plains'],
                'is_popular' => true,
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'name' => 'Ngorongoro Crater',
                'slug' => 'ngorongoro-crater',
                'country' => 'Tanzania',
                'region' => 'Northern',
                'description' => 'A UNESCO World Heritage Site, this massive volcanic caldera hosts dense wildlife populations including the rare black rhino.',
                'image_url' => 'https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=800&q=80',
                'visa_required' => false,
                'visa_type' => null,
                'flight_duration' => '1 hour from Arusha',
                'best_season' => 'June - October',
                'highlights' => ['World\'s Largest Caldera', 'Black Rhinos', 'Dense Wildlife', 'UNESCO Heritage Site'],
                'is_popular' => true,
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'name' => 'Mount Kilimanjaro',
                'slug' => 'mount-kilimanjaro',
                'country' => 'Tanzania',
                'region' => 'Northern',
                'description' => 'Africa\'s highest peak and the world\'s tallest free-standing mountain. A challenging but rewarding climb through diverse ecosystems.',
                'image_url' => 'https://images.unsplash.com/photo-1609766857071-0e0b3a9f4c19?w=800&q=80',
                'visa_required' => false,
                'visa_type' => null,
                'flight_duration' => '1 hour from Arusha',
                'best_season' => 'January - March, June - October',
                'highlights' => ['Africa\'s Highest Peak', '7 Climbing Routes', 'Diverse Ecosystems', 'Snow-Capped Summit'],
                'is_popular' => true,
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'name' => 'Zanzibar Beaches',
                'slug' => 'zanzibar-beaches',
                'country' => 'Tanzania',
                'region' => 'Coastal',
                'description' => 'Pristine white sand beaches, crystal clear waters, and rich Swahili culture. Perfect for relaxation, diving, and cultural exploration.',
                'image_url' => 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80',
                'visa_required' => false,
                'visa_type' => null,
                'flight_duration' => '30 minutes from Dar es Salaam',
                'best_season' => 'June - October, December - February',
                'highlights' => ['Stone Town', 'Spice Tours', 'Dolphin Tours', 'Historic Slave Markets'],
                'is_popular' => true,
                'is_active' => true,
                'sort_order' => 11,
            ],
            [
                'name' => 'Tarangire National Park',
                'slug' => 'tarangire-national-park',
                'country' => 'Tanzania',
                'region' => 'Northern',
                'description' => 'Famous for its massive elephant herds and ancient baobab trees. Less crowded than other parks with excellent bird watching.',
                'image_url' => 'https://images.unsplash.com/photo-1549366021-9f761d450615?w=800&q=80',
                'visa_required' => false,
                'visa_type' => null,
                'flight_duration' => '2 hours from Arusha',
                'best_season' => 'June - October',
                'highlights' => ['Large Elephant Herds', 'Ancient Baobab Trees', 'Bird Watching', 'Less Crowded'],
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 12,
            ],
            [
                'name' => 'Lake Manyara National Park',
                'slug' => 'lake-manyara-national-park',
                'country' => 'Tanzania',
                'region' => 'Northern',
                'description' => 'Known for tree-climbing lions, diverse bird life, and stunning alkaline lake views. Compact park perfect for day trips.',
                'image_url' => 'https://images.unsplash.com/photo-1549366021-9f761d450615?w=800&q=80',
                'visa_required' => false,
                'visa_type' => null,
                'flight_duration' => '1.5 hours from Arusha',
                'best_season' => 'June - October',
                'highlights' => ['Tree-Climbing Lions', 'Flamingos', 'Diverse Bird Life', 'Alkaline Lake'],
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 13,
            ],
        ];

        foreach ($destinations as $destination) {
            Destination::updateOrCreate(
                ['slug' => $destination['slug']],
                $destination
            );
        }

        $this->command->info('Destinations seeded successfully.');
    }
}
