<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Service;
use App\Models\Destination;
use App\Models\TeamMember;

class PageSeeder extends Seeder
{
    public function run(): void
    {
        // ── Services ─────────────────────────────────────────────
        $services = [
            // Travel
            ['name'=>'Flight Ticketing','slug'=>'flight-ticketing','category'=>'travel','icon'=>'bi-airplane-fill','icon_color'=>'#3b82f6','short_description'=>'Competitive fares on all major airlines. Business, economy, and group travel to 50+ worldwide destinations.','features'=>['All major airlines','Same-day issuance','Business & economy','Group bookings','24/7 support'],'is_featured'=>true,'sort_order'=>1],
            ['name'=>'Visa Assistance','slug'=>'visa-assistance','category'=>'travel','icon'=>'bi-passport-fill','icon_color'=>'#8b5cf6','short_description'=>'Professional visa processing for UAE, UK, USA, Schengen, China, India, Turkey and more. We handle the paperwork.','features'=>['UAE, UK, USA, Schengen','Express processing','Document checklist','Application support','High approval rate'],'is_featured'=>true,'sort_order'=>2],
            ['name'=>'Hotel Booking','slug'=>'hotel-booking','category'=>'travel','icon'=>'bi-building-fill','icon_color'=>'#10b981','short_description'=>'Carefully selected hotels across all destinations. Budget to luxury options with best available rates.','features'=>['Budget to 5-star','Best rate guarantee','Airport proximity','Cancellation support','Corporate rates'],'is_featured'=>false,'sort_order'=>3],
            ['name'=>'Airport Transfers','slug'=>'airport-transfers','category'=>'travel','icon'=>'bi-taxi-front-fill','icon_color'=>'#f59e0b','short_description'=>'Reliable pickup and drop-off services at major airports. Available 24/7 with professional drivers.','features'=>['24/7 availability','Professional drivers','Meet & greet','Group vehicles','Real-time tracking'],'is_featured'=>false,'sort_order'=>4],
            // Legal
            ['name'=>'Litigation & Arbitration','slug'=>'litigation','category'=>'legal','icon'=>'bi-bank2','icon_color'=>'#ef4444','short_description'=>'Experienced legal representation in civil, commercial, and criminal matters before courts at all levels in Tanzania.','features'=>['Civil litigation','Criminal defence','Commercial disputes','Alternative dispute resolution','Appellate advocacy'],'is_featured'=>true,'sort_order'=>5],
            ['name'=>'Contract Drafting & Review','slug'=>'contract-review','category'=>'legal','icon'=>'bi-file-earmark-text-fill','icon_color'=>'#0ea5e9','short_description'=>'Professional contract preparation, review, and advisory for individuals, businesses, and organizations.','features'=>['Employment contracts','Business agreements','Lease agreements','MOU & partnership deeds','Legal due diligence'],'is_featured'=>false,'sort_order'=>6],
            ['name'=>'Immigration Law','slug'=>'immigration-law','category'=>'legal','icon'=>'bi-globe-americas','icon_color'=>'#6366f1','short_description'=>'Comprehensive immigration services including work permits, residence permits, and citizenship applications.','features'=>['Work permits','Residence permits','Citizenship applications','Investor visas','Immigration appeals'],'is_featured'=>false,'sort_order'=>7],
            // Research
            ['name'=>'Research & Proposal Writing','slug'=>'research-writing','category'=>'research','icon'=>'bi-journal-text','icon_color'=>'#d97706','short_description'=>'Academic and organizational research, concept notes, proposals, and feasibility studies of the highest quality.','features'=>['Academic research','Feasibility studies','Concept notes','Grant proposals','Market analysis'],'is_featured'=>true,'sort_order'=>8],
            ['name'=>'Business Plans & Reports','slug'=>'business-plans','category'=>'research','icon'=>'bi-graph-up-arrow','icon_color'=>'#10b981','short_description'=>'Investor-ready business plans, strategic reports, and organizational assessments for startups and established firms.','features'=>['Investor-ready plans','Financial projections','Market research','Strategic planning','Organizational assessments'],'is_featured'=>false,'sort_order'=>9],
            // Registration
            ['name'=>'BRELA Company Registration','slug'=>'brela-registration','category'=>'registration','icon'=>'bi-building-add','icon_color'=>'#004a99','short_description'=>'Fast and professional business registration with BRELA — sole proprietorships, partnerships, limited companies, and more.','features'=>['Sole proprietorship','Partnerships','Limited companies','Name reservation','Business licence'],'is_featured'=>true,'sort_order'=>10],
            ['name'=>'NGO / CSO Registration','slug'=>'ngo-registration','category'=>'registration','icon'=>'bi-people-fill','icon_color'=>'#ec4899','short_description'=>'Complete NGO, CSO, and foundation registration with relevant government authorities in Tanzania.','features'=>['NGO registration','CSO registration','Foundation setup','Annual returns','Compliance advisory'],'is_featured'=>false,'sort_order'=>11],
            ['name'=>'Tax Compliance & TIN','slug'=>'tax-compliance','category'=>'registration','icon'=>'bi-receipt-cutoff','icon_color'=>'#64748b','short_description'=>'TIN registration, tax compliance support, and advisory for individuals and organizations with TRA Tanzania.','features'=>['TIN registration','VAT registration','Tax clearance','Filing support','TRA advisory'],'is_featured'=>false,'sort_order'=>12],
            // ICT
            ['name'=>'ICT Solutions','slug'=>'ict-solutions','category'=>'ict','icon'=>'bi-cpu-fill','icon_color'=>'#06b6d4','short_description'=>'Technology solutions for businesses — website development, software systems, networking, and IT consultancy.','features'=>['Website development','Software systems','Network setup','IT consultancy','Digital transformation'],'is_featured'=>false,'sort_order'=>13],
        ];

        foreach ($services as $s) {
            Service::updateOrCreate(['slug' => $s['slug']], $s);
        }

        // ── Destinations ──────────────────────────────────────────
        $destinations = [
            ['name'=>'Dubai','slug'=>'dubai','country'=>'UAE','region'=>'Middle East','description'=>'The jewel of the Middle East — iconic skyline, world-class shopping, and pristine beaches. Visa processing available with fast turnaround.','image_url'=>'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80','visa_required'=>true,'visa_type'=>'Tourist/Visit Visa','flight_duration'=>'~5 hours','best_season'=>'Oct – Apr','highlights'=>['Burj Khalifa','Dubai Mall','Desert Safari','Gold Souk'],'is_popular'=>true,'sort_order'=>1],
            ['name'=>'London','slug'=>'london','country'=>'United Kingdom','region'=>'Europe','description'=>'From Buckingham Palace to the West End, London offers world-class culture, history, and business opportunities. UK visa support available.','image_url'=>'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&q=80','visa_required'=>true,'visa_type'=>'UK Standard Visitor Visa','flight_duration'=>'~9 hours','best_season'=>'May – Sep','highlights'=>['Big Ben','Buckingham Palace','Oxford Street','The Shard'],'is_popular'=>true,'sort_order'=>2],
            ['name'=>'Istanbul','slug'=>'istanbul','country'=>'Turkey','region'=>'Europe/Asia','description'=>'Where East meets West — breathtaking mosques, vibrant bazaars, and stunning Bosphorus views. Turkish e-visa available easily.','image_url'=>'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?w=800&q=80','visa_required'=>true,'visa_type'=>'Turkey e-Visa','flight_duration'=>'~6 hours','best_season'=>'Apr – Jun, Sep – Nov','highlights'=>['Hagia Sophia','Grand Bazaar','Bosphorus Cruise','Topkapi Palace'],'is_popular'=>true,'sort_order'=>3],
            ['name'=>'New York','slug'=>'new-york','country'=>'USA','region'=>'Americas','description'=>'The city that never sleeps — iconic skyline, Times Square, Broadway shows, and endless opportunities. US visa processing support.','image_url'=>'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&q=80','visa_required'=>true,'visa_type'=>'US B1/B2 Visitor Visa','flight_duration'=>'~18 hours','best_season'=>'Apr – Jun, Sep – Nov','highlights'=>['Statue of Liberty','Times Square','Central Park','Broadway'],'is_popular'=>true,'sort_order'=>4],
            ['name'=>'Beijing','slug'=>'beijing','country'=>'China','region'=>'Asia','description'=>'Ancient wonders meet modern marvels — the Great Wall, Forbidden City, and a thriving business hub. China visa assistance available.','image_url'=>'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800&q=80','visa_required'=>true,'visa_type'=>'China Tourist Visa (L)','flight_duration'=>'~10 hours','best_season'=>'Apr – May, Sep – Oct','highlights'=>['Great Wall','Forbidden City','Summer Palace','Tiananmen'],'is_popular'=>true,'sort_order'=>5],
            ['name'=>'Mumbai','slug'=>'mumbai','country'=>'India','region'=>'Asia','description'=>'Gateway to India — the city of dreams. Business hub, Bollywood, vibrant street food, and rich culture. India visa processing available.','image_url'=>'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&q=80','visa_required'=>true,'visa_type'=>'India e-Visa','flight_duration'=>'~4 hours','best_season'=>'Nov – Feb','highlights'=>['Gateway of India','Marine Drive','Dharavi','Bollywood Studios'],'is_popular'=>false,'sort_order'=>6],
            ['name'=>'Paris','slug'=>'paris','country'=>'France','region'=>'Europe','description'=>'The City of Light — romance, world-class cuisine, art, and the iconic Eiffel Tower. Schengen visa processing available.','image_url'=>'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80','visa_required'=>true,'visa_type'=>'Schengen Visa','flight_duration'=>'~9 hours','best_season'=>'Apr – Jun, Sep – Oct','highlights'=>['Eiffel Tower','Louvre','Champs-Élysées','Palace of Versailles'],'is_popular'=>true,'sort_order'=>7],
            ['name'=>'Riyadh','slug'=>'riyadh','country'=>'Saudi Arabia','region'=>'Middle East','description'=>'The rapidly transforming capital of Saudi Arabia — rich history, modern architecture, and growing business opportunities.','image_url'=>'https://images.unsplash.com/photo-1586724237569-f3d0c1dee8c6?w=800&q=80','visa_required'=>true,'visa_type'=>'Saudi e-Visa','flight_duration'=>'~4 hours','best_season'=>'Nov – Feb','highlights'=>['Kingdom Centre','Diriyah','National Museum','Edge of the World'],'is_popular'=>false,'sort_order'=>8],
            ['name'=>'Doha','slug'=>'doha','country'=>'Qatar','region'=>'Middle East','description'=>'A stunning blend of tradition and modernity. Doha is a hub for business and tourism with excellent connectivity worldwide.','image_url'=>'https://images.unsplash.com/photo-1548263594-a71ea65a8598?w=800&q=80','visa_required'=>true,'visa_type'=>'Qatar Visa on Arrival','flight_duration'=>'~4 hours','best_season'=>'Nov – Mar','highlights'=>['Souq Waqif','Museum of Islamic Art','The Pearl','Katara Village'],'is_popular'=>false,'sort_order'=>9],
            ['name'=>'Nairobi','slug'=>'nairobi','country'=>'Kenya','region'=>'Africa','description'=>'East Africa\'s business capital and safari gateway. Close to home with no visa required for Tanzanians.','image_url'=>'https://images.unsplash.com/photo-1611348524140-53c9a25263d6?w=800&q=80','visa_required'=>false,'visa_type'=>'Visa-free for Tanzanians','flight_duration'=>'~1 hour','best_season'=>'Year-round','highlights'=>['Maasai Mara','Nairobi National Park','Karen Blixen Museum','City skyline'],'is_popular'=>false,'sort_order'=>10],
            ['name'=>'Addis Ababa','slug'=>'addis-ababa','country'=>'Ethiopia','region'=>'Africa','description'=>'Africa\'s diplomatic capital and home to the African Union. A growing hub for trade, culture, and regional connectivity.','image_url'=>'https://images.unsplash.com/photo-1626779950219-cef0b80a1b3b?w=800&q=80','visa_required'=>true,'visa_type'=>'Ethiopia e-Visa','flight_duration'=>'~1.5 hours','best_season'=>'Oct – Jan','highlights'=>['National Museum','Entoto Hills','Merkato','African Union HQ'],'is_popular'=>false,'sort_order'=>11],
            ['name'=>'Amsterdam','slug'=>'amsterdam','country'=>'Netherlands','region'=>'Europe','description'=>'The Venice of the North — canals, tulips, museums, and a relaxed atmosphere. Schengen visa required.','image_url'=>'https://images.unsplash.com/photo-1534351590666-13e3e96b5702?w=800&q=80','visa_required'=>true,'visa_type'=>'Schengen Visa','flight_duration'=>'~9 hours','best_season'=>'Apr – Sep','highlights'=>['Anne Frank House','Rijksmuseum','Canal Cruise','Keukenhof'],'is_popular'=>false,'sort_order'=>12],
        ];

        foreach ($destinations as $d) {
            Destination::updateOrCreate(['slug' => $d['slug']], $d);
        }

        // ── Team Members ──────────────────────────────────────────
        $team = [
            ['name'=>'Emmanuel Kasimbagu','title'=>'Founder & Managing Director','department'=>'Leadership','bio'=>'A visionary leader with over 15 years of experience in legal practice, business consultancy, and travel services. Emmanuel founded Kasimbagu with the mission of providing accessible, professional services to individuals and organizations across East Africa.','photo_url'=>'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=400&q=80&fit=crop&crop=face','sort_order'=>1],
            ['name'=>'Fatuma Mwakatobe','title'=>'Head of Legal Services','department'=>'Legal','bio'=>'A seasoned advocate with expertise in commercial law, immigration, and organizational legal compliance. Fatuma has successfully represented hundreds of clients before Tanzanian courts.','photo_url'=>'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&q=80&fit=crop&crop=face','sort_order'=>2],
            ['name'=>'James Mringo','title'=>'Senior Travel Consultant','department'=>'Travel','bio'=>'With 10 years in the travel industry, James specializes in complex multi-destination itineraries, visa processing, and corporate travel management for East African clients.','photo_url'=>'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&q=80&fit=crop&crop=face','sort_order'=>3],
            ['name'=>'Grace Kimaro','title'=>'Research & Consultancy Lead','department'=>'Research','bio'=>'Grace holds a Master\'s in Development Studies and specializes in research writing, proposal development, and organizational capacity building for NGOs and government institutions.','photo_url'=>'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&q=80&fit=crop&crop=face','sort_order'=>4],
            ['name'=>'David Shayo','title'=>'Company Registration Specialist','department'=>'Registration','bio'=>'An expert in business registration, compliance, and corporate governance. David has guided over 300 businesses through successful registration with BRELA, TRA, and other regulatory bodies.','photo_url'=>'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&q=80&fit=crop&crop=face','sort_order'=>5],
            ['name'=>'Amina Hassan','title'=>'Client Relations Manager','department'=>'Operations','bio'=>'Amina ensures every client receives world-class service from the first inquiry to final delivery. She manages client onboarding, follow-ups, and satisfaction across all departments.','photo_url'=>'https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&h=400&q=80&fit=crop&crop=face','sort_order'=>6],
        ];

        foreach ($team as $t) {
            TeamMember::updateOrCreate(['name' => $t['name']], $t);
        }
    }
}
